version: "3.9"
services:
  node:
    build:
      context: .
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 3000:3000
      - 8000:8000
    command: tail -f /dev/null
    volumes:
      - node-modules:/usr/local/lib/node_modules
      - ./src:/src
      - ./work:/work
volumes:
  node-modules:
