version: "3.9"
services:
  node:
    build:
      context: .
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - node-modules-global:/usr/local/lib/node_modules
      - node-modules-site:/src/site/node_modules
      - ./src:/src
      - ./work:/work
volumes:
  node-modules-global:
  node-modules-site:
