version: "3.9"
services:
  node:
    build:
      context: .
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - "./src:/src"
      - "./work:/work"
